const screens={
  wallet:{src:'swissxo-wallet-funded.webp',title:'Your wallet. Your keys.',description:'See your assets and balances together, with send, receive and swap journeys in the wallet interface. Keys are generated and held on your device.',alt:'SwissXO wallet showing five assets with illustrative balances'},
  markets:{src:'swissxo-markets.jpg',title:'A window into the market.',description:'Explore assets, categories and watchlists. Follow prices and market movements, with a clear distinction between the assets you watch and the ones your wallet can hold.',alt:'SwissXO market screen showing asset categories, prices and watchlist stars; prices are a snapshot'},
  wallets:{src:'swissxo-wallets-funded.webp',title:'Your wallets. Together.',description:'Switch between your SwissXO wallet and existing wallets in one place. Each wallet keeps its own recovery context, including wallets used with Trust Wallet or MetaMask.',alt:'SwissXO wallet manager showing the SwissXO account and an additional Trust Wallet account with illustrative funds'},
  portfolio:{src:'swissxo-portfolio-funded.webp',title:'See how it all adds up.',description:'Understand how your balance is distributed across assets. The portfolio view brings individual holdings and allocation into one clear picture.',alt:'SwissXO illustrative portfolio allocation across USDT, USDC, Ethereum, Tron and Bitcoin, totalling $111,068.40'}
};
const views=[...document.querySelectorAll('[data-xo-view]')];
const panel=document.querySelector('#xo-preview-panel');
function selectScreen(key){const screen=screens[key];if(!screen)return;views.forEach(tab=>{const selected=tab.dataset.xoView===key;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1});panel.setAttribute('aria-labelledby',`xo-tab-${key}`);const image=document.querySelector('#xo-gallery-image');image.src=`./${screen.src}`;image.alt=screen.alt;document.querySelector('#xo-view-title').textContent=screen.title;document.querySelector('#xo-view-description').textContent=screen.description}
function keyboardTabs(tabs,select,key){tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>select(tab.dataset[key]));tab.addEventListener('keydown',event=>{let next;if(['ArrowRight','ArrowDown'].includes(event.key))next=(index+1)%tabs.length;if(['ArrowLeft','ArrowUp'].includes(event.key))next=(index-1+tabs.length)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();select(tabs[next].dataset[key]);tabs[next].focus()}})})}
keyboardTabs(views,selectScreen,'xoView');
const communication={
  chat:'<div class="message-date">ILLUSTRATIVE CONVERSATION</div><div class="message-bubble incoming">A little more space for us.<small>10:02</small></div><div class="message-bubble outgoing">And a little less for everyone else.<small>10:03 ✓✓</small></div><div class="encryption-note">End-to-end encrypted<br /><span>Conversation history stored locally</span></div>',
  voice:`<div class="call-preview"><div class="call-avatar" aria-hidden="true">XO</div><h4>Closer through conversation.</h4><p>End-to-end encrypted voice</p><div class="waveform" aria-hidden="true">${[12,24,16,34,25,40,18,30,16,26,12].map((height,i)=>`<i style="--height:${height}px;--delay:${i*-.15}s"></i>`).join('')}</div><p>Voice call preview</p></div>`,
  video:'<div class="video-preview"><div><div class="call-avatar" aria-hidden="true">XO</div><p>A face-to-face connection.<br />End-to-end encrypted video.</p></div><span class="video-self">You</span></div>'
};
const commTabs=[...document.querySelectorAll('[data-comm]')];
function selectCommunication(key){if(!communication[key])return;commTabs.forEach(tab=>{const selected=tab.dataset.comm===key;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1});const comm=document.querySelector('#comm-panel');comm.setAttribute('aria-labelledby',`comm-tab-${key}`);comm.innerHTML=communication[key]}
keyboardTabs(commTabs,selectCommunication,'comm');
const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('#navigation');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus()}});
